version: "3"
services:
  app:
    build: "."
    volumes:
      - "./app:/app"
    working_dir: "/app"
    command: "npm run dev"
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
  broker:
    image: "rabbitmq:3.12.2-management-alpine"
    volumes:
      - "./broker/data:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    user: "1000:1000"
