version: "3"
services:
  bot:
    build:
      context: "./bot"
    volumes:
      - "./bot/app:/app"
      - "./storage:/storage"
    working_dir: "/app"
    command: "npm run dev"
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      BROKER_USERNAME: $BROKER_USERNAME
      BROKER_PASSWORD: $BROKER_PASSWORD
      BROKER_HOST: "broker"
      BROKER_PORT: "5672"
      DEV_ENVIRONMENT: "local"
      DEV_DISCORD_GUILD_ID: $DEV_DISCORD_GUILD_ID
      DB_HOST: "db"
      DB_PORT: "27017"
      DB_DATABASE: $MONGO_DB
      DB_USERNAME: $MONGO_USERNAME
      DB_PASSWORD: $MONGO_PASSWORD
      DB_COLLECTION: $MONGO_COLLECTION
  transcriber:
    build:
      context: "./transcriber"
    volumes:
      - "./transcriber/app:/app"
      - "./storage:/storage"
    working_dir: "/app"
    command: "python /app/src/main.py"
    environment:
      BROKER_USERNAME: $BROKER_USERNAME
      BROKER_PASSWORD: $BROKER_PASSWORD
      BROKER_HOST: "broker"
      BROKER_PORT: "5672"
      DB_HOST: "db"
      DB_PORT: "27017"
      DB_DATABASE: $MONGO_DB
      DB_USERNAME: $MONGO_USERNAME
      DB_PASSWORD: $MONGO_PASSWORD
      DB_COLLECTION: $MONGO_COLLECTION
      LANGUAGE: $TRANSCRIBER_LANGUAGE
  broker:
    image: "rabbitmq:3.12.2-management-alpine"
    volumes:
      - "./broker/data:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    user: "1000:1000"
    environment:
      RABBITMQ_DEFAULT_USER: $BROKER_USERNAME
      RABBITMQ_DEFAULT_PASS: $BROKER_PASSWORD
  db:
    image: "mongo:4.4.23"
    volumes:
      - "mongo:/data/db"
      - "./db/config/mongo.conf:/etc/mongo.conf"
      - "./db/init:/docker-entrypoint-initdb.d"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
      USERNAME: $MONGO_USERNAME
      PASSWORD: $MONGO_PASSWORD
      COLLECTION: $MONGO_COLLECTION
    command: "--config /etc/mongo.conf"
    expose:
      - "27017"
volumes:
  mongo:
