version: "3"
services:
  app:
    build: "."
    volumes:
      - "./app:/app"
    working_dir: "/app"
    command: "npm run dev"
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
  broker:
    image: "eclipse-mosquitto:2.0.15"
    volumes:
      - "./broker/config:/mosquitto/config"
      - "./broker/data:/mosquitto/data"
      - "./broker/log:/mosquitto/log"
    ports:
      - "1883:1883"
    expose:
      - "1883"
    user: "1000:1000"
