version: "3"
services:
  bot:
    build:
      context: "./bot"
    volumes:
      - "./bot/app:/app"
    working_dir: "/app"
    command: "npm run dev"
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      BROKER_USERNAME: $BROKER_USERNAME
      BROKER_PASSWORD: $BROKER_PASSWORD
      BROKER_HOST: "broker"
      BROKER_PORT: "5672"
      DEV_ENVIRONMENT: "local"
      DEV_DISCORD_GUILD_ID: $DEV_DISCORD_GUILD_ID
  transcriber:
    build:
      context: "./transcriber"
    volumes:
      - "./transcriber/app:/app"
    working_dir: "/app"
    command: "python /app/src/main.py"
    environment:
      BROKER_USERNAME: $BROKER_USERNAME
      BROKER_PASSWORD: $BROKER_PASSWORD
      BROKER_HOST: "broker"
      BROKER_PORT: "5672"
  broker:
    image: "rabbitmq:3.12.2-management-alpine"
    volumes:
      - "./broker/data:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    user: "1000:1000"
    environment:
      RABBITMQ_DEFAULT_USER: $BROKER_USERNAME
      RABBITMQ_DEFAULT_PASS: $BROKER_PASSWORD
